### ISSUE TITLE
Completely external device

### ISSUE THREAD

**Issue by stevexyz** [holmatic/zx-iot-video#1]
Would it be possible to attach to MIC instead of pin 16 of ULA? There is a resistor and a capacitor in the middle but also on the wespi side... maybe with some wespi adaptation might be possible!

If possible, this would allow for a completely external module, with power coming before to this "ext waspi" and then from it to ZX (maybe even a bit more stabilized), and then 2 cables fromwespi to mic and ear plugs!

**Comment by holmatic** [comment]
> 
> 
> Would it be possible to attach to MIC instead of pin 16 of ULA? There is a resistor and a capacitor in the middle but also on the wespi side... maybe with some wespi adaptation might be possible!
> 
> If possible, this would allow for a completely external module, with power coming before to this "ext waspi" and then from it to ZX (maybe even a bit more stabilized), and then 2 cables fromwespi to mic and ear plugs!

Due to the resitor and capacitor you mentioned, the MIC output of a ZX has a very weak signal - somewhere in the microvolt range. Thus one would need a very sensitive low-noise preamp with fixed gain to get back to levels that wespi could use.  That preamp circuit would probably need some substantial analogue electronics black magic to get it working reliably.

**Comment by stevexyz** [comment]
I might have some skills as a software magician (1krealchess is on that side) or apprentice ones for digital electronics (e.g. microtron or super micro relay computer), but unfortunately I'm pretty green on analogue circuits.
Anyway, if technically possible there might be out there some wizard ones that might help!
PS: forgot to mention on first post, but really compliments for this extremely nice project!

**Comment by hagen-git** [comment]
Thank you, holmatic, for this impressive project - I come from the [TZXDuino side (for a Jupiter Ace in an FPGA)](https://gitlab.com/dev-hp/TZXDuino/-/tree/unswitch) and discovered zx-iot-video on the ZX-TEAM forum. I'm also not very well versed in analog electronics, but please allow me to chime in with my 2 cents. 

> stevexyz: 
> Would it be possible to attach to MIC instead of pin 16 of ULA?

Very likely this would not work for the video signal:

- McKlaud's PDF schematic (thanks!) shows that the ZX81 MIC output circuit has a low-pass filter (C11/R27) with a cutoff frequency around 3.39kHz ([calculated with this website](https://electronicbase.net/low-pass-filter-calculator/)).  
- To me, this looks like it is deliberately designed to filter out the high-frequency video components (up to 6.5MHz) from the ULA output signal, to avoid these high frequencies from interfering with (or even damaging) a cassette recorder connected to the MIC output.

For all ZX81 'tape' functions, just using MIC and EAR connections ('record' and 'play') should work. And this already gives you an impressive amount of functionality (not only a moving-parts-free cassette recorder emulation, but also a WiFi-accessible Web Server to manage ZX81 files on, and an ingenious menu system that runs on the ZX81). 

If the audio level really is too low, there are ready-made LM386 audio amplifier modules made for the Arduino that you can use to boost the MIC signal. The circuit used in a cheap 80's mono cassette recorder is not much different (and I used my ZX81 with one of these cheap cassette recorders around 1982-1984, before I got a 'Schneider CPC464', so I know it worked).

> holmatic:
> Due to the resitor and capacitor you mentioned, the MIC output of a ZX has a very weak signal - somewhere in the microvolt range. 

For a small TV-to-Composite conversion project, [I made a simple video amplifier to bring a weak composite (VBS/BAS) signal to the voltage level a TV set needs](https://gitlab.com/repair1/conic-tg-621). 
- Disclaimer: I am also not an electrical engineer or Radio/TV repair technician, so my electronics knowledge is patchy. 
-  What I could do for this video amplifier was thus very limited: 
    - I found a simple video amplifier circuit on the internet, 
    - and put this on a breadboard (to at least see if it can work at all). 
    - It did not work initially, because it was designed for a different battery voltage (than available on the target platform). 
    - Then I simulated the circuit with NI Multisim (they have a 45-day test license) and tweaked the component values until everything looked good with power in the required voltage range, 
    - then checked it on the breadboard circuit. 
    - After this worked fine, I soldered the components from the breadboard onto a stripboard PCB. 
- [It turned out quite well in the end.](https://gitlab.com/repair1/conic-tg-621/-/blob/master/media/conic-2020-07-26-vbs-amp.jpg)

> holmatic:
> Thus one would need a very sensitive low-noise preamp with fixed gain to get back to levels that wespi could use. That preamp circuit would probably need some substantial analogue electronics black magic to get it working reliably.

I agree, the video signal part left on the MIC output after the low-pass filter is probably really, really low, and therefore difficult to re-generate. 

If you need the ZX81 video part (and who does not want a nice TFT or VGA output?), a direct connection to the ULA is the best way to get a good signal.


Another 'plug-and-play' option (cable-connection only) would be to replace the ZX81 RF output modulator with a composite (VBS) output (ca. 1.073V differential). Then you could connect the ZX81/composite output with the WESPI and amplify the composite signal on the WESPI side. 

For my Jupiter Ace FPGA project, I will probably test if I can make this work - I don't have a ZX81 anymore, and the ability to use composite-to-TFT/VGA would be really nice. I don't need this quickly (the FPGA version has VGA output), but it would be nice to be able to do small Jupiter Ace things on the 320*240 TFT (saves me some VGA monitor schlepping).

For the audio signal from Papilio One Jupiter Ace to the ZX-Wespi-Video/jupiter_ace_native (i.e. MIC output), I use this circuit (inspired by the Jupiter Ace schematics): [Papilio One Jupiter Ace - Wespi Circuit](https://github.com/hagen-git/zx-iot-video/blob/jupiter_ace_native/doc/Wespi-P1Jupiter_schem.png)

- So far I tested the 'MIC' part, i.e. SAVE/BSAVE from the Jupiter Ace (FPGA emulation) to the Wespi, and that works fine. 
- Now that this direction works well, one of my next tasks will be to try and make the ZX-Wespi-Video 'tape' output (EAR part) work for the Jupiter Ace. 
- The menu system is a somewhat harder nut to crack (FORTH instead of BASIC), but initially I most urgently need the IP address of the Wespi. Maybe I can just write it into a pre-made 'comment' word that the Jupiter Ace can LOAD from the Wespi.
